config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  
  get '/users/:id', :to => 'users#show', :as => :user
  get 'home/about'
  get '/' => 'users#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @photos = Photo.all.order("created_at DESC")
  end

  def show
  end

  def new
    @photo = current_user.photos.build
  end

  def edit
  end

  def create
    @photo = current_user.photos.build(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def correct_user
      @photo = current_user.photos.find_by(id: params[:id])
      redirect_to photos_path, notice: "Not authorized to edit this photo" if @photo.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show	
  		@user = User.find(params[:id])
	end

	def index
    	@users = User.all.order("updated_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar-default navbar-general navbar-fixed-top navbar-shrink">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Aurora</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', home_about_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to 'New', new_photo_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Join", new_user_registration_path %></li>
        <% end %>
        <!-- TODO: implement facebook login -->
      </ul>
    </div>
  </div>
</nav>

app/views/home/_header_homepage.html.erb
<nav class="navbar-default navbar-homepage navbar-fixed-top navbar-shrink">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Aurora</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', home_about_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to 'New', new_photo_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Join", new_user_registration_path %></li>
        <% end %>
        <!-- TODO: implement facebook login -->
      </ul>
    </div>
  </div>
</nav>

app/views/home/_otherheaders.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-shrink" id="otherheaders">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Aurora</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', home_about_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to 'New', new_photo_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Join", new_user_registration_path %></li>
        <% end %>
        <!-- TODO: implement facebook login -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_signup.html.erb
<section id="signinreminder">
</section>

app/views/home/_topsection.html.erb
  <header>
    <div class="container" id="topsection">
      <div class="intro-text">
        <div class="intro-lead-ind"><h1>Welcome to Aurora!</h1></div>
        <div class="intro-heading"><p>Find professional photographers here</p></div>
        <% if user_signed_in? %>  
            <%= link_to "Find More", photos_path, class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %> 
          <%= link_to "Discover", photos_path, class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </header> 

app/views/home/about.html.erb
<h1>Super Cool Photographor Platfrom -----> Aurora!</h1>
<p>papapa here</p>

app/views/home/index.html.erb
<div class="jumbotron center">
  <h1>Welcome to Aurora!</h1>
  <p>find cool stuff here...</p>

<!--   <%= link_to "Login", new_user_session_path, class: "btn btn-default" %>  -->
  
  <% if user_signed_in? %>
  	<%= link_to "Find More", photos_path, class: "btn btn-primary" %>

  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %> 
    <%= link_to "Discover", photos_path, class: "btn btn-default" %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aurora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_page?("/") %>
	<%= render '/home/header_homepage' %>
	<%= render '/home/topsection' %>
	<%= render '/home/signup' %>
<% else %>
	<%= render '/home/header' %>
<% end %>

<div class="container">

<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, html: { multipart: true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br/>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>  

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>Editing Photo</h1></div>
  <div class="panel-body">

  <%= render 'form' %>
  </div>
</div>	

<div class="panel-footer">
  <%= link_to 'Show', @photo %> |
  <%= link_to 'Back', photos_path %>
</div>

app/views/photos/index.html.erb
<div id="photos" class="transitions-enabled">
	<% @photos.each do |photo| %>

	<div class="box">
		<div class="panel panel-default">
  		<%= link_to image_tag(photo.image.url()), photo %><br/>
			<div class="panel-body">
	    		<strong>Photographer:</strong>
	    		<%= photo.user.email %><br/>
    		</div>
  		</div>
	</div>
	
	<% end %>
</div>
<br>

app/views/photos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>New Photo</h1></div>
  <div class="panel-body">

  <%= render 'form' %>
  </div>
</div>

<div class="panel-footer"><%= link_to 'Back', photos_path %></div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-offset-0 col-md-12">

		<div class="panel panel-default">
			<div class="panel-heading center col-md-12">
				<%= image_tag @photo.image.url, :class => "col-md-12" %>
			</div>

			<div class="panel-heading center">
			  <strong>Description:</strong>
			  <%= @photo.description %>
				<br/>
				<% if @photo.user == current_user  %>
					<%= link_to 'Edit', edit_photo_path(@photo) %>
					<%= link_to 'Destroy', @photo, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
				<%= link_to 'Back', photos_path %>

			</div>
		</div>

	</div>
</div>

app/views/users/index.html.erb
<div id="photos" class="transitions-enabled">
	<% @users.each do |user| %>

	<div class="box">
		<div class="panel panel-default">
			<% if user.photos.any? %>
				<%= link_to image_tag(user.photos.first.image.url(:medium)), user %><br/>
			<% end %>

			<div class="panel-body">
	    		<strong>Photographer:</strong>
	    		<%= link_to user.email, user %><br/>
    		</div>
  		</div>
	</div>
	
	<% end %>
</div>
<br>

app/views/users/show.html.erb
<head>
	<link rel="stylesheet" type="text/css" href="slick/slick.css"/>
	<link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
</head>

<body>
	<div class="row">
		<div class="one-time">
			<% @user.photos.each do |photo| %>

			<div class="box">
				<div class="panel panel-default">
					<%= link_to image_tag(photo.image.url(:medium)), photo %>
					<div class="panel-body center">
			    		<%= photo.description %><br/>
		  		</div>
				</div>
			</div>
			
			<% end %>
		</div>
		<br/>

    <div class="input-group">
      <input type="text" class="form-control" placeholder="Type message to book...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Book!</button>
      </span>
    </div>
	</div>

</body>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Aurora</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', welcome_about_path %></li>

        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <!-- TODO need to update login path -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>